import { createSlice  } from '@reduxjs/toolkit';
import { RootState,  } from '../../app/store';

export interface CounterState {
  isShow: boolean;
}

const initialState: CounterState = {
  isShow: false,
};


export const modalSlice = createSlice({
  name: 'modal',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    showModal: (state) => {
        state.isShow = true
    },
    hiddenModal: (state) => {
        state.isShow = false
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
   
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.

});

export const { showModal, hiddenModal } = modalSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectIsShowModal = (state: RootState) => state.modal.isShow;



export default modalSlice.reducer;
